# Generated by Django 5.2.4 on 2025-07-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("pic", models.CharField(max_length=300)),
                ("age", models.IntegerField()),
                ("diseases", models.CharField(max_length=100)),
            ],
        ),
    ]
